import type { Student } from './types';

export const TIME_SLOTS = [
  '9:00 AM - 10:00 AM',
  '10:00 AM - 11:00 AM',
  '11:00 AM - 12:00 PM',
  '1:00 PM - 2:00 PM',
  '2:00 PM - 3:00 PM'
];

export const STUDENTS: Student[] = [
{ id: '1', name: 'JOEL JOJY MANALAYIL', rollNo: 1 },
{ id: '2', name: 'SANJU THOMAS ABRAHAM', rollNo: 2 },
{ id: '3', name: 'ABCEL THOMAS', rollNo: 3 },
{ id: '4', name: 'ABHIJITH BIJU', rollNo: 4 },
{ id: '5', name: 'ABHIJITH P', rollNo: 5 },
{ id: '6', name: 'ABHINAV SUNNY', rollNo: 6 },
{ id: '7', name: 'ADITHYAN R', rollNo: 7 },
{ id: '8', name: 'AJOY SUNNY', rollNo: 8 },
{ id: '9', name: 'AKSHAI SUBASH', rollNo: 9 },
{ id: '10', name: 'ALPHA ELSA SISIL', rollNo: 10 },
{ id: '11', name: 'AMAL BAIJU', rollNo: 11 },
{ id: '12', name: 'AMAL BENNY', rollNo: 12 },
{ id: '13', name: 'ANSON JOSE', rollNo: 13 },
{ id: '14', name: 'ANTONY K THOMAS', rollNo: 14 },
{ id: '15', name: 'BIBINE PAUL THOMAS', rollNo: 15 },
{ id: '16', name: 'BINOY ANIL', rollNo: 16 },
{ id: '17', name: 'FATHIMA SHUKKOOR', rollNo: 17 },
{ id: '18', name: 'JITHU S JAYAN', rollNo: 18 },
{ id: '19', name: 'JOEL VARGHESE JOBY', rollNo: 19 },
{ id: '20', name: 'JOYAL JOE JOSEPH', rollNo: 20 },
{ id: '21', name: 'K ADARSH ANISH', rollNo: 21 },
{ id: '22', name: 'KEN SAINS', rollNo: 22 },
{ id: '23', name: 'LESHA VINOD ALI', rollNo: 23 },
{ id: '24', name: 'NANDANA KUNJUMON', rollNo: 24 },
{ id: '25', name: 'NAVANEETH K SHAJI', rollNo: 25 },
{ id: '26', name: 'NIKHIL JAYANAND', rollNo: 26 },
{ id: '27', name: 'NIRANJITHA ROSE SEBASTIAN', rollNo: 27 },
{ id: '28', name: 'NITHIN R', rollNo: 28 },
{ id: '29', name: 'PARTHIV P KURUP', rollNo: 29 },
{ id: '30', name: 'PARVATHI REVI', rollNo: 30 },
{ id: '31', name: 'POOJA PREMKUMAR', rollNo: 31 },
{ id: '32', name: 'ROBIN ROY', rollNo: 32 },
{ id: '33', name: 'ROBSY VARGHESE', rollNo: 33 },
{ id: '34', name: 'ROSHAN P ROY', rollNo: 34 },
{ id: '35', name: 'ROSLYN MARIA JOHN', rollNo: 35 },
{ id: '36', name: 'SAMITH JOSE', rollNo: 36 },
{ id: '37', name: 'SAMVRUTHA SUNIL', rollNo: 37 },
{ id: '38', name: 'SANIYA T S', rollNo: 38 },
{ id: '39', name: 'SHINU. K. MATHEW', rollNo: 39 },
{ id: '40', name: 'SHRIKALA.V.S', rollNo: 40 },
{ id: '41', name: 'SIVANAND S', rollNo: 41 },
{ id: '42', name: 'SRAVAN V', rollNo: 42 },
{ id: '43', name: 'TOM THOMAS', rollNo: 43 },
{ id: '44', name: 'UDISH B', rollNo: 44 },
{ id: '45', name: 'YOUHAN ABRAHAM GIFTY', rollNo: 45 },
{ id: '46', name: 'PRANAV. A. V', rollNo: 46 },
{ id: '47', name: 'PRAJITH J', rollNo: 47 }